---
title: "Pogie_June6"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggtree)
library(ape)
library(gdata)

#Loading the data
pogie_all_TREE <- read.tree("1547_Sep7.tre")
data.set <- read.xls("1547_newnames.xlsx")
write.tree(pogie_all_TREE, file = "1547_TREE.newick")
```


```{r}
library(scales)library(tidyverse)
library(magrittr)
library(phytools)

data.set[data.set==""] <- NA_character_

#Plotting the tree
ggtree(midpoint.root(pogie_all_TREE),layout = 'circular') %<+% data.set[,-1] + 
  geom_tiplab2(aes(color=subgenus),align=FALSE, hjust = -0.1, size = 1) + 
  geom_nodelab(aes(x=branch, label=label, subset = !is.na(as.numeric(label)) & as.numeric(label) >70), vjust=-.5, size=2) +  theme(legend.position="right") +  scale_color_manual(values =c("#9590FF", "#00BF7D", "#E76BF3", "#00B0F6", "#D89000", "#969696"))
  

#Plotting an ultrametric tree
ggtree(midpoint.root(pogie_all_TREE),layout = 'circular',  branch.length = "none") %<+% data.set[,-1] + 
  geom_tiplab2(aes(color=subgenus),align=FALSE, hjust = -0.1, size = 1) + theme(legend.position="right") +  scale_color_manual(values =c("#9590FF", "#00BF7D", "#E76BF3", "#00B0F6", "#D89000", "#969696"))
  
# Gheatmap
library(phangorn)
t1 <- ggtree(midpoint(pogie_all_TREE),layout = 'circular', branch.length = "none") %<+% data.set[,-1] + geom_tippoint(aes(color=subgenus),align=FALSE, hjust = -0.1, size = 5) +
   scale_color_manual(values =c("#9590FF", "#00BF7D", "#E76BF3", "#00B0F6", "#D89000", "#969696"))

t1


# Removing taxa names and adding them as row names in data frame

df.1 <- data.set[,-1]
rownames(df.1) <- df.1[,1]
df.1 <- df.1[,-1]

df.1[is.na(df.1)] <- 0

# Plotting the tree
library(ggnewscale)
library(wesanderson)
library(RColorBrewer)

nb.cols <- c("#FFFFFF","#1B9E77", "#897932", "#C8611F", "#8D6B86", "#9B58A5", "#DD2E8D", "#A66753", "#70A61B", "#BBA90B")
p1 <- t1 + new_scale_fill()
p1 <- gheatmap(p1, subset(df.1, select=c(1)), width=0.09, offset=0.00000000001) + 
  scale_fill_manual(values = nb.cols, name="Island")
p1


forest.col <- c("#FFFFFF", "#8FD744FF", "#31688EFF")
p2 <- p1 + new_scale_fill()
p2 <- gheatmap(p2, subset(df.1, select=c(3)), width=0.09, offset=23) + 
  scale_fill_manual(values = forest.col, name="Forest")
p2


type.col <- c("#FFFFFF", "#0D0887FF", "#CC4678FF", "#F89441ff")
p3 <- p2 + new_scale_fill()
p3 <- gheatmap(p3, subset(df.1, select=c(6)), width=0.09, offset=46) + scale_fill_manual(values = type.col, name="Source")
p3

bio.colors <- c("#FFFFFF", "#FF0000", "#00A08A", "#F2AD00")
p4 <- p3 + new_scale_fill()
p4 <- gheatmap(p4, subset(df.1, select=c(4)), width=.09, offset=69) + scale_fill_manual(values = bio.colors)
p4
```




